### ISSUE TITLE
Request: Capture transparent window and getting frame without transparency 

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#42]
Hello,
I feel that the thread was not clear for us
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/41

Since I am not sure you understand my request and I am not sure I understand you, I want to clearly by start a topic on dedicated thread.

I wrote in comment: [here](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/41#issuecomment-535068806)

I wan't you to know what exactly I am doing and need so you will have the best feedback and information. In case you going to fix a bug that will break it, or you going to build API that I don't need, I try to write the best description I can.

**a)**
In order that I will able to do what I want to do, I set transparency to `hwndTarget`.
`hwndTarget` is for example this window
![image](https://user-images.githubusercontent.com/17680514/65650176-603aa500-e012-11e9-93f6-0c3667ad6872.png)

Or it can be any other window.

**b)**
Next, I set transparency:
```cpp
SetLayeredWindowAttributes(hwndTarget, 0, 1, LWA_ALPHA)
```
After that, the window is invisible but you still can interact with it (you just don't see it).

**c)**
Next, I create child window for `hwndTarget` called `hwndDisplay`
```cpp
hwndDisplay = CreateWindowEx(WS_EX_NOACTIVATE | 0x080000 | WS_EX_TRANSPARENT | WS_EX_LAYERED /*| WS_EX_TOPMOST*/, nDisplayLayerBase::ccharClassName, NULL, 0x80000000,
0, 0, this->rectLayer->right - this->rectLayer->left, this->rectLayer->bottom - this->rectLayer->top, hwndTarget, NULL, nDisplayLayerBase::hInstance, NULL);
```
(`rectLayer` is RECT structure that is the position and size of `hwndTarget`)

**d)**
Next, I initilize and start using the capture API. 
I start capture session for `hwndTarget` (That is transparent now) and getting frames.
Even if the window is transparent, the frame display the window without transparency.

While on the monitor, the window is invisible 
![image](https://user-images.githubusercontent.com/17680514/65650409-65e4ba80-e013-11e9-90b8-443a426bb979.png)

I still get this textrue:
![image](https://user-images.githubusercontent.com/17680514/65650418-75640380-e013-11e9-9115-6423d2d10b27.png)

**e)**
Next, I extract the raw pixels from the textrue and processing the pixels using my algorithm:
For each background pixel, the algorithm set RGBA value of (0,0,0,0) . For other pixels, it change RGBA value according to the situation.

Next, using a drawing API, I draw the processed frame on `hwndDisplay`. This will draw the RGBA values. any pixel with color (0,0,0,0) will be transparent so it is as if that pixels was not draw.
Other pixels will show such as text

end result:
![image](https://user-images.githubusercontent.com/17680514/65650659-7a758280-e014-11e9-8fdc-08dc7273035f.png)

*My concern*
According to thread, I understand that there is bug that the capture API ignoring transparency.
In step **d** I need exactly this behavior.

I understand right that you see this behavior as a bug? If yes then please add this option as a feature to enable or disable in the API.

If not then everything is fine.

Thanks

**Comment by robmikh** [comment]
> According to thread, I understand that there is bug that the capture API ignoring transparency.

This is incorrect. The bug was about clearing the D3D texture before drawing, it did not effect the mechanics of window rendering. For example, if you had a non-rectangular window, the areas of the buffer where the window is not present would previously be opaque black and would now be transparent black.

This:
![alpha-incorrect](https://user-images.githubusercontent.com/7089228/66025672-e429dc80-e4ab-11e9-914f-6ac4a7925afb.png)

Will become this:
![alpha-correct](https://user-images.githubusercontent.com/7089228/66025679-e8ee9080-e4ab-11e9-8797-bfb28407c481.png)

If the window is transparent, then it's alpha values will be preserved.  For example:

This:
![alpha2-incorrect](https://user-images.githubusercontent.com/7089228/66025823-379c2a80-e4ac-11e9-94b7-7ab87cc4f4f7.png)

Will become this:
![alpha2-correct](https://user-images.githubusercontent.com/7089228/66025832-3d920b80-e4ac-11e9-93c6-5b691fdbc3a5.png)

If for some reason you really need it look like we cleared with opaque black, you should be able to blend the image with a solid black texture to get the same thing as before.

With that said, feel free to run your application on a recent insider build and let us know if you have any issues. In the scenario you described, this change shouldn't effect you. This is because the Notepad window is drawn as fully opaque.

Hopefully this should be a bit clearer now. I'm going to close this issue, since we can't really address an issue without a repro. Feel free to reopen this issue if you find a different bug that prevents your scenario from working.

**Comment by gileli121** [comment]
Thanks!
