### ISSUE TITLE
Stop capturing mouse cursor in screen capture

### ISSUE THREAD

**Issue by NickThissen** [microsoft/Windows.UI.Composition-Win32-Samples#44]
Is there a way to stop capturing the mouse cursor in the WPF screen capture sample? 

I found the following blog post that mentions a new IsCursorEnabled api:
https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/#ptMq3QzycLCpvCuT.97

However I cannot find this anywhere. Is it simply not exposed in the C# side of things or something?

**Comment by robmikh** [comment]
It's an API that will appear in the next release of Windows, and should be currently available in insider builds. Take a look at the `insider` branch from the [Win32CaptureSample](https://github.com/robmikh/Win32CaptureSample/tree/insider). You can see it in action [here](https://github.com/robmikh/Win32CaptureSample/blob/da3ff3f4d807fd73e09d9bee20349c4fbce675e8/Win32CaptureSample/App.cpp#L185).

Apologies in advanced, that branch is a little stale.

**Comment by NickThissen** [comment]
Thanks. I am using the C# WPF version, is it available there or will it be available in the future? I am running on the insider build.

**Comment by robmikh** [comment]
Consuming WinRT APIs in a C# non-UWP app is a bit different. You need to provide the metadata (.winmd) that will be used when compiling the application. We do this by using the [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) nuget package. Currently the only published version is for the current retail release.

In order to use a newer version of the metadata, you'll need to remove the reference to the nuget package and add a reference to the metadata in your SDK folder. You may also have to add a reference to the SDK's version of System.Runtime.WindowsRuntime.dll.

Here's an example of where to find the metadata and runtime dll:
* `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\<SDK Version here>\Windows.winmd`
* `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.WindowsRuntime.dll`

I would recommend moving back to the nuget package once the next release has been shipped.

**Comment by Cimplex** [comment]
Once I found the new the new [Windows 10 SDK Preview (18990)](https://blogs.windows.com/windowsdeveloper/2019/10/01/windows-10-sdk-preview-build-18990-available-now/) this was relatively easy to implement.

**System.Runtime.WindowsRuntime.dll** is required for `IAsyncOperation` to be awaitable (e.g. the `GraphicsCapturePicker.PickSingleItemAsync`).

I can't tell you how much time you saved me, thank you!

**Comment by gileli121** [comment]
@robmikh 
Will this API `IsCursorEnabled` will work on Windows 10 `19H2` release or I will have to wait a lot of time for `20H1` release?

I understand that it will be included in `20H1` and it will take forever until this update will come out

**Comment by robmikh** [comment]
This API will start being available in 20H1, I don't believe any new capture features are showing up in 19H2.

**Comment by robmikh** [comment]
Closing this issue, let us know if you run into anything else!
