### ISSUE TITLE
Correct way to check for IsCursorCaptureEnabled support?

### ISSUE THREAD

**Issue by jpark37** [microsoft/Windows.UI.Composition-Win32-Samples#50]
Existing code looks like this:

`const winrt::Windows::Graphics::Capture::GraphicsCaptureSession session = frame_pool.CreateCaptureSession(item);`

We will probably want to do something like this:

`if (???) { session.IsCursorCaptureEnabled(cursor_enabled); }`

What's the correct test here? Stepping back, is this the correct test for determining if window capture is supported at all?

`return winrt::Windows::Foundation::Metadata::ApiInformation::IsApiContractPresent(L"Windows.Foundation.UniversalApiContract", 8);`

**Comment by robmikh** [comment]
To check if capture is supported at all use the following:

```
auto supported = 
    winrt::Windows::Foundation::Metadata::ApiInformation::IsTypePresent(L"Windows.Graphics.Capture.GraphicsCaptureSession") && 
    winrt::Windows::Graphics::Capture::GraphicsCaptureSession::IsSupported();
```

The first part checks to see if the capture API is present at all. The second part checks whether screen capture is present (e.g. This currently returns false on the Xbox). 

To check for individual feature availability, use the following:

```
auto supported = 
    winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(
        L"Windows.Graphics.Capture.GraphicsCaptureSession", 
        L"IsCursorCaptureEnabled");
```

PS: It is technically possible to use the capture API if `IsSupported` returns false, but only by using `GraphicsCaptureItem::CreateFromVisual` (your own content).

**Comment by jpark37** [comment]
I'll use these. Thanks.

**Comment by robmikh** [comment]
No problem!

**Comment by jpark37** [comment]
For window capture support as a whole, I'm going back to UniversalApiContract >= 8 for the time being. GraphicsCaptureSession exists on 1809, but IGraphicsCaptureItemInterop does not, so we were falsely reporting support for that version.

**Comment by robmikh** [comment]
Ah sorry, I should have mentioned that. We introduced the capture API before we introduced the Win32 specific interface. Since you rely on that, checking support for UniversalApiContract 8 is certainly the way to go.

**Comment by glemselenselv** [comment]
Shouldn't 19041 come with _IsCursorCaptureEnabled_ support? I tried to use that in a _netstandard2.0_ project defining this:
<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />

ApiInformation.IsTypePresent(@"Windows.Graphics.Capture.GraphicsCaptureSession") results to **TRUE** but
ApiInformation.IsPropertyPresent(@"Windows.Graphics.Capture.GraphicsCaptureSession", @"IsCursorCaptureEnabled") is **FALSE**

Am I doing something wrong?

**Comment by GuanjunZhuo** [comment]
if (Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 10))
{
GraphicsCaptureSession.IsCursorCaptureEnabled = value; // maybe check 
}
The way sometimes does not work in C# constructor. Even if you set judgment, there may still be errors and errors will pop up. It may be because C# will check all the property in advance, so I use reflection to avoid it, AS SHOW BELOW
if (Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent(
"Windows.Foundation.UniversalApiContract", 10))
{
       var aa = session.GetType().GetProperty("IsCursorCaptureEnabled");
       if (aa != null)
             aa.SetValue(session,false);
}
Welcome to discuss.

**Comment by GuanjunZhuo** [comment]
'if(Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 10))
{
    GraphicsCaptureSession.IsCursorCaptureEnabled = value; // maybe check 
}'

The way sometimes does not work in C# constructor.
Even if you set judgment, there may still be errors and errors will pop up.
It may be because C# will check all the property in advance, 
so I use reflection to avoid it, AS SHOW BELOW

'if (Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent(
"Windows.Foundation.UniversalApiContract", 10))
{
    var aa = GraphicsCaptureSession.GetType().GetProperty("IsCursorCaptureEnabled");
    if (aa != null)
        aa.SetValue(GraphicsCaptureSession,false);
}'
Welcome to discuss.

**Comment by GuanjunZhuo** [comment]
'''
`if(Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 10))
{
    GraphicsCaptureSession.IsCursorCaptureEnabled = value; // maybe check 
}
'''

The way sometimes does not work in C# constructor.
Even if you set judgment, there may still be errors and errors will pop up.
It may be because C# will check all the property in advance, 
so I use reflection to avoid it, AS SHOW BELOW
'''
if (Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent(
"Windows.Foundation.UniversalApiContract", 10))
{
    var aa = GraphicsCaptureSession.GetType().GetProperty("IsCursorCaptureEnabled");
    if (aa != null)
        aa.SetValue(GraphicsCaptureSession,false);
}
'''
Welcome to discuss.
