### ISSUE TITLE
Use this Samples with CefSharp has a problem

### ISSUE THREAD

**Issue by langrenjeff** [microsoft/Windows.UI.Composition-Win32-Samples#55]
In my WPF application, I want use window capture by hwnd, and also my application is using CEFSharp.Wpf, if I first invoke Cef.Initialize(), then call IGraphicsCaptureItemInterop.CreateForWindow()  to get a GraphicsCaptureItem, it will throw a exception. If I don't invoke Cef.Initialize(), it work well. 
By the way, use GraphicsCapturePicker.PickSingleItemAsync() to get a GraphicsCaptureItem will work well whatever use cef or not.
Is there any conflict between IGraphicsCaptureItemInterop.CreateForWindow and CEF? 
I know IGraphicsCaptureItemInterop is a COM interface, but I can't find what it is actually.
My application is base on .net framework 4.7.2, and CEFSharp version is 79.1.360.
Hope someone give me some advice, thanks.

Second Question: How to make OnFrameArrived callback running in a non-UI thread?

**Comment by robmikh** [comment]
Could you share more about the exception that you're seeing? I tried to add CefSharp to a test app and couldn't get it to load properly, so I'm unable to reproduce what you're seeing.

If the picker works but CreateForWindow did not, it likely means that Initialize is modifying your process token to be LowIL or you're calling CreateForWindow from a LowIL process started by CEF. We currently do not support calling CreateForWindow or CreateForMonitor from a LowIL process. If this is indeed what you're hitting, I'd expect the exception to be something like E_ACCESSDENIED.

**Comment by robmikh** [comment]
To have the FrameArrived event call you on a thread other than the one you created the frame pool on, you need to create the frame pool using `CreateFreeThreaded` instead of `Create`. Note that if you do this, any callbacks provided to the frame pool must be agile. I think this works out of the box in .NET Core (I remember having issues with .NET Framework, but I haven't tried it recently), definitely works for UWP C# and C++/WinRT.

**Comment by langrenjeff** [comment]
hello robmikh, the LowIL process is the key.
The exception type is System.Runtime.InteropServices.SEHException, and Message could be "external components occurred exception" in English, my language of VS2017 is not English .
In app.manifest, I set requestedExecutionLevel, so 
if level is asInvoker and run cef, work well;
if level is requireAdministrator and NOT run cef, it is also work well;
if level is requireAdministrator and run cef, it is NOT work;
My application is set as requireAdministrator when I debug before;
Will CEF change the integrity level of my process? And Why?
By finally, I found the cause of the problem. Thanks a lot.

**Comment by langrenjeff** [comment]
Take about my second question. Use Direct3D11CaptureFramePool.CreateFreeThreaded() make OnFrameArrived invoked in a non-ui thread, but this thread is not controlled by my code;
I tried call 
`capture = new BasicCapture(device, item);
capture.StartCapture();`
in a non-ui thread, named ThreadA, use Direct3D11CaptureFramePool.Create() in BasicCapture(), then FrameArrived event is not invoked at all. I was hoping FrameArrived event invoked in my ThreadA. Can I make FrameArrived callback run in a specified thread, such as a thread that I new it in code. 
By the way, Can you talk something about  CoreMessagingHelper.CreateDispatcherQueueControllerForCurrentThread? Is it necessary to capture window?

**Comment by robmikh** [comment]
Chromium likely drops the integrity level of the process that runs javascript, since it can be arbitrary code running on your machine. I'd be careful about what you run if you're running it in any elevated fashion.

As for your second question, yes that is the intended behavior. The callback will fire on the frame pool's internal worker thread if you create it with `CreateFreeThreaded`. If you wish to do the processing on a thread of your choosing you have two choices:

1. Use `Create` to create the frame pool, but create it on the thread that you wish to process the callback on. This thread is required to have a DispatcherQueue (and to be pumping messages). This is the mechanism by which we can execute on your thread.
2. If you have some other mechanism in which you can execute code on another thread, then create the frame pool with `CreateFreeThreaded` and then use that mechanism you have to signal the other thread. A way to simplify the marshaling is to just signal the thread and have the other thread call `TryGetNextFrame` on the frame pool. This approach does not require the DispatcherQueue.
