### ISSUE TITLE
Screen capture API works faster on integrated GPU and slower on dedicated GPU

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#61]
Hello, while debugging the reason why the codes

```cpp
framePool = Direct3D11CaptureFramePool::Create(
	graphicDevice->device,
	DirectXPixelFormat::B8G8R8A8UIntNormalized,
	2,
	size);

captureSession = framePool.CreateCaptureSession(captureItem);


captureLastSize = size;
frameArrived = framePool.FrameArrived(auto_revoke, { this, &CaptureLayer_Win10API::Callback_OnFrameArrived });


.... 

captureSession.StartCapture();

```

```cpp
void Callback_OnFrameArrived(
	winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool const& sender,
	winrt::Windows::Foundation::IInspectable const& args)
{

	if (isClosed) return;


	using namespace winrt;
	using namespace Windows::Graphics::DirectX;
	using namespace Windows::Graphics::DirectX::Direct3D11;

	auto frame = sender.TryGetNextFrame();

	return;
}
```

works slower than your original example on 4K (noticeable by eye on 4K only)

I found that the root cause is the 3d device I use.
I choose intentionally to create `ID3D11Device` on the dedicated GPU that is NVIDIA GTX 1050TI in my case.

I found that if the `ID3D11Device` is based on the integrated video that is INTEL GPU card, there is noticeable performance improvement in the capture rate.

Is there any reason why it works faster with a GPU that less powerful?

**Comment by robmikh** [comment]
The issue is that on dual GPU systems, you can get caught up in the issue that some content is on one GPU and some on the other. Applications can even theoretically use composition surfaces from both GPUs at the same time in their app. You also have the possibility of choosing a different GPU than the one the DWM is using to scan out to the screen. In these cases we end up making copies between the GPUs by pulling bits into system memory which will be slower.

Are you on a laptop? Often the Intel integrated part is actually the thing that is scanning out to the panel. 

As a general rule of thumb, things will be faster if you use the GPU the DWM is using to scan out.

**Comment by gileli121** [comment]
Thanks for your answer. 
You confirmed what I thought.

I tried to think that maybe it is a good idea to scan the frame into the integrated GPU just because it runs 2 times faster. But I see that I anyway need to move it to Nvidia GPU for processing, so better to let the API just write in Nvidia GPU directly.

Is there an option to force that DWM will not use the integrated GPU so the capture will come directly from the Nvidia GPU?

**Comment by robmikh** [comment]
I don't believe that's configurable at the moment.

**Comment by gileli121** [comment]
I suggest (if it is not too complex) that the API will tell the system (DWM) to render the window on the GPU where the texture is saved. It should improve performance a lot.
Any copy between GPU and RAM is slow.. I saw it myself how much it kill performance.

**Comment by renanalencar** [comment]
Hi, all! Any news concerning this? I notice the same problem when using a laptop with integrated GPU Intel Arc.

**Comment by robmikh** [comment]
Unfortunately this will be an issue with any multi-adapter system. I have no updates at this time.
