### ISSUE TITLE
Some picked windows return a size of 0 x 0, causing a crash in "CreateSwapChainForComposition"

### ISSUE THREAD

**Issue by MartinClementson** [microsoft/Windows.UI.Composition-Win32-Samples#65]
Hello.
I noticed this issue when using the Win32CaptureSample project. When picking a window to share, there is a scenario where some windows capture item reports a size of 0 x 0, even if the window is restored and visible at the front. This will cause the function CreateSwapChainForComposition to throw a hresult_error exception. I can't say for sure that it is the size that causes the crash, but it is the difference between the windows that work and the ones that don't.

The window I've encountered this on 100% of the time is of the app  ["Inno Setup Compiler"](https://jrsoftware.org/isinfo.php).

I tried this with the Win32CaptureSample running on SDK/Win10 version 10.0.19041.0.

I've tried to create the swap chain with a fixed size (e.g 1024x1024) in these scenarios, which does not produce a crash, but there is no output.

The thing that confuses me is that the picker is able to capture the window in the miniature view,. Correct me if I am wrong, but I was thinking that the view in the picker might be using the same capture item that is returned upon selection? (it's a wild guess).

Does anyone have any suggestions on how to work around this? Can you exclude windows from the picker, (which I would have to do in my own app if it fails, to let the user know that a window simply can't be captured)?

Additionally, trying to create a CaptureItem with the HWND of the app window in question creates a debug abort() error in "CreateForWindow", probably due to the same reason (although the HWND reports having the actual size of the window.)

As a slightly related question, is there a way to get the HWND from the Graphics Capture Item that the picker returns? The only way I can see is to use the item.DisplayName and do [FindWindowA](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowa). I'm wondering if that is thread-safe and if the DisplayName will always be the same as the WindowName needed for FindWindowA, so that it can be a reliable solution?

Thanks in advance!
M

**Comment by robmikh** [comment]
Hmmm... the Inno Setup Compiler seems to be an odd case. It has two windows, one with a class of TCompileForm and one with a class of TApplication:

![image](https://user-images.githubusercontent.com/7089228/88961434-e094ec80-d259-11ea-9bf5-1152253478d8.png)

The TApplication window has a size of (0, 0), while the TCompileForm window seems to have a reasonable size. Unfortunately the shell has decided that TApplication is actually the main window for this application. That's why it shows up in the picker and doesn't throw an exception when trying to create a capture item from its window handle. We don't have a mechanism to exclude windows from the picker, nor do we expose a way to get the window handle from a capture item.

You're not getting anything back from capturing the TApplication window because it doesn't have content (I'm not sure why it's there...). Interestingly, creating a thumbnail via DwmRegisterThumbnail seems to work, and is what the picker does for its preview. This is a fairly odd corner case and I'll file a bug internally.

**Comment by MartinClementson** [comment]
That is some excellent detective work Rob. Thanks for looking into it. I guess it was only that unlikely corner case, I must've gotten it confused with exceptions being thrown when trying to create capture for other windows that were not supported (I used my own window enumeration and selection method until I moved it to the picker, which filtered the bad ones out, except for this one.)

The reason I am looking to get the HWND from the item is that I've noticed that if you capture a window, and that window is minimized, it won't always show up until you restore the window. I didn't find a way to do that with the item alone.

Thank you
